# we have ile with a dictionary named employee. 
# We would like to record information about multiple employees.
# Convert the dictionary named employee to an array named employees.

# Just below data from questions.

employee:
  name: john
  gender: male
  age: 24

# Ans.

employees:
  - name: john
    gender: male
    age: 24
    
