# As per the details given in the table below, you can see that, the web servers are linux based hosts and the db server is a Windows machine.

# Update the inventory /home/bob/playbooks/inventory to add a similar entry for server4.company.com host.
# Find the required details from the table below.

# ---------------------------------------------------------------------------
# |  Alias |        HOST         | Connection | User          | Password     | 
# ---------------------------------------------------------------------------
# |  web1  | server1.company.com |    ssh     | root          | Password123! |
# ---------------------------------------------------------------------------
# |  web2  | server2.company.com |    ssh     | root          | Password123! |
# ---------------------------------------------------------------------------
# |  web3  | server3.company.com |    ssh     | root          | Password123! |
# ---------------------------------------------------------------------------
# |  db1   | server4.company.com |    winrm   | administrator | Dbp@ss123!   |
# ---------------------------------------------------------------------------

# Note: For Linux based hosts, use ansible_ssh_pass parameter and,
# for Windows based hosts, use ansible_password parameter.


