---
- name: Install softwares
  hosts: all
  become: yes
  vars:
    packages:
      - name: nginx
        required: false
      - name: mysql
        required: false
      - name: apache
        required: false

  tasks:
  - name: Install "{{ item.name }}" on debian
    apt:
      name: "{{ item.name }}"
      state: present

    when: item.required == true
     
    loop: "{{ packages }}"
